### ISSUE TITLE
add terms 'medication role' and 'medication material'

### ISSUE THREAD

**Issue by cstoeckert** [biobanking/biobanking#1]
For our local competency question, we need to add a general term to cover drugs and dietary supplements. For a different project we came up with 'medication' to also cover anything (e.g., blood transfusions) used for clinical treatment. 
medication role: A role borne by some material entity which can be delivered/administrated into some organism and the role is realized during a clinical treatment process aiming to treat symptoms, signs or diagnosed disease.
medication material: A material entity that is bearer of a medication role.

**Comment by cstoeckert** [comment]
Approved by email response from JZ and MB.

**Comment by zhengj2007** [comment]
Terms were added
