### ISSUE TITLE
NTR: data items - specimen storage terms

### ISSUE THREAD

**Issue by ddooley** [biobanking/biobanking#102]
GenEpiO has a few **Specimen Storage Terms** that would fit well in OBIB.  They are in a "data" tab in following Google sheet, in ROBOT table format, but we understand OBIB might not have that going for this kind of entry.
(`GenEpiO ID (temporary)` and `Curation Notes` annotations are for curation phase of work only.

https://docs.google.com/spreadsheets/d/1SiVgFDy9jOoFIhywvLjYLMBLqJsZ0B9An9170RYpQRM/edit#gid=2146269079&range=A3

label
specimen storage duration
specimen storage temperature
specimen storage location

This originates in OBI term request: https://github.com/obi-ontology/obi/issues/1577

**Comment by mbrochhausen** [comment]
Thanks! Those look good. We will discuss those in this week's OBIB meeting.

**Comment by mbrochhausen** [comment]
This was discussed with Damion present in the OBIB call on April 27. We are waiting to hear back from him and the group.

**Comment by ddooley** [comment]
I have feedback already!  All the recommendations are fine:
- we can reuse the OBIB "Storage temperature setting" instead; 
- we like the "Pre-analysis specimen storage duration" label.
- we don’t need the MIxS:0000455 etc ids annotated in OBIB directly.
- specimen storage location can be an "information content entity" directly.
Cheers,
Damion & Emma & Rhiannon

**Comment by mbrochhausen** [comment]
Excellent! That was fast. We are getting to work on adding those terms and we will update the issue tracker item once they are in OBIB.

**Comment by jmwhorton** [comment]
I've added the two new terms and made a pull request #105 

@ddooley, could you take a look and make sure everything is represented as intended?

**Comment by ddooley** [comment]
All good!

**Comment by cmrn-rhi** [comment]
This issue has been addressed and can be closed now. Confirmed with @ddooley
