### ISSUE TITLE
faulty superclass for 'urine specimen' and 'blood specimen'

### ISSUE THREAD

**Issue by mbrochhausen** [biobanking/biobanking#13]
Hi,

it seems we have a taxonomy bug in OBIB (might come from OMIABIS): 'urine specimen' and 'blood specimen" are subclass to 'tissue specimen'. That seems counterintuitive to me. If this is a bug, I can totally change that in the owl file, I just wanted to make sure it is a bug and not a feature.

**Comment by mbrochhausen** [comment]
I think we need to discuss this. What do they users think? They people I
worked with always were very very particular about keeping fluids and
tissue separate.

There is another issue with the axiom on tissue specimen: Using 'gross
anatomical part" from CARO does not allow to be specific, like saying
"liver tissue specimen' since CARO is so sparse (48 classes). It would be
much better to use UBERON.

Best,
Mathias

**Comment by cstoeckert** [comment]
these have been brought up and discussed on the June 20th call. Both issues will be addressed.
'tissue specimen' -> 'specimen from organism'
CARO: 'gross anatomical part' -> UBERON: 'material anatomical entity'
