### ISSUE TITLE
Mapping from OBIB to MIABIS

### ISSUE THREAD

**Issue by mbrochhausen** [biobanking/biobanking#14]
This is the initial draft of a mapping. We will be in touch with the MIABIS developers during summer and finalize this:
https://docs.google.com/spreadsheets/d/11olx-9XWpzIan2z99N_vnwURbSNr4Sw7Iq_WZqgI5TM/edit?usp=sharing

**Comment by cstoeckert** [comment]
From Sarah Bost / Mathias (April 11, 2019 email: List of terms to add to OBIB)

pathogen (IDO_0000528) or pathogen role (IDO_0000405)
given name (IAO_0020016)
family name (IAO_0020017)
ORCID (APOLLO_SV_00000496)

Note that these will be added automatically with current Ontodog file (include all children of 'eligibility criterion'
health status inclusion criterion (OBI_0002453)
gravidity inclusion criterion (OBI_0002456)
defined population inclusion criterion (OBI_0002460)
clinically relevant lifestyle inclusion criterion (OBI_0002454)
clinically relevant exposure inclusion criterion (OBI_0002455)

**Comment by cstoeckert** [comment]
Added requested import terms
pathogen (IDO_0000528)
given name (IAO_0020016)
family name (IAO_0020017)
ORCID (APOLLO_SV_00000496)
https://github.com/biobanking/ontology/commit/e78d169c3514acceb611c3c3f9797207d1859471

**Comment by cstoeckert** [comment]
Imported inclusion criteria from OBI https://github.com/biobanking/ontology/commit/4ff220929264075b9f152fdb2b894f450761c445
