### ISSUE TITLE
duplicate specimens

### ISSUE THREAD

**Issue by cstoeckert** [biobanking/biobanking#17]
Upon importing 'specimens collected from organism' from OBI, we now have duplicates for:
bone marrow specimen OMIABIS_0000049 // OBI_0002512
cerebrospinal fluid OMIABIS_0001075 // OBI_0002502
faeces specimen OMIABIS_0001076 // OBI_0002503
saliva specimen OMIABIS_0001077 // OBI_0002507
The duplicate OBI terms are defined consistently with the new terms including logical definitions for inferencing under 'specimen from organism':
('has role' some 'specimen role')
 and ('derives from' some 
    ('material anatomical entity' or 'anatomical cluster'))

Proposal is to obsolete the OMIABIS terms above with 'obsolescence reason specification' 'term imported'

Note: will also need to import 'obsolescence reason specification' and its instances.

**Comment by mbrochhausen** [comment]
I am wondering whether we should not just declare the OMIABIS terms to be equivalent with the OBI terms and then put a note on the OMIABIS terms to use the OBI terms for new development instead. Obsoleting might create problems with the Swedish group.
What do you think>

**Comment by zhengj2007** [comment]
I'd prefer to deprecate the OMIABIS terms following OBI (GO) deprecation policy. So, the OMIABIS terms ID (IRI) are still available in OBIB. But in the 'obsolescence reason specification' choose 'term imported' and add equivalent OBI ID. If we want, we can also add annotation 'has_alternative_id' associated with imported OBI terms and pointed to OMIABIS ID as what PATO did. Using this approach, the users of OMIABIS can be aware that the terms have been replaced by OBI terms. It will facilitate biobank data integration with OBIB. To set equivalent using equivalent classes are quite annoying. When I built BCGO using external ontologies with importing in GO:cell and CL:cell which are equivalent class, it causes inconsistency.
Alternative approach is removing those duplicated OBI terms and replaced by OMIABIS terms if people think IRIs with OMIABIS domain are fine.

**Comment by mbrochhausen** [comment]
Ok, if we use the term imported strategy adding the OBI ID, I could probably live with it. **Please make sure you inform the European group of that change!**
It would be neat to know the actual reason why the BCGO example causes inconstitencies. I dare say it has something to do with other axioms, not the equivalence axiom. In which case it would be that maybe those terms are indeed not equivalent between GO and CL. I doubt that we would create the same problem. But, go ahead...

**Comment by cstoeckert** [comment]
Informed the MIABIS group and proposed a method a deprecation. There was agreement after clarification that the new terms did not restrict the specimens to an anatomic site but rather provided an UBERON-defined anatomic class (e.g., bone marrow) as derivation. This has been done for the new OBIB release.
