### ISSUE TITLE
Stained Fixed Tissue Slides Specimens

### ISSUE THREAD

**Issue by nhaubein** [biobanking/biobanking#19]
I would like to request the following types as children to fixed tissue slide specimen (OMIABIS_0000052):

- H&E stained fixed tissue slide specimen
- IHC stained fixed tissue slide specimen 

IHC = immunohistochemistry
H&E = Hematoxylin and eosin stain or haematoxylin and eosin stain

Background on H&E staining can be found here:
http://www.histalim.com/accueil/activities/our-services/histology/hematoxylin-eosin-2/

Background on IHC can be found here:
http://www.agilent.com/cs/library/technicaloverviews/public/08002_ihc_staining_methods.pdf

Thank you.

Ned Haubein
Penn Medicine

**Comment by cstoeckert** [comment]
Propose making:
H&E slide staining: a staining process using hematoxylin and eosin. The staining is applied to fixed specimens on slides to observe the whole structure and morphology of cells in a tissue; nuclei are stained dark blue/purple while cytoplasm is stained pink. 
Def. Source: http://www.histalim.com/accueil/activities/our-services/histology/hematoxylin-eosin-2/
	Specified input: fixed tissue slide specimen 
	Specified output: H&E stained fixed tissue slide specimen.
H&E stained fixed tissue slide specimen: A fixed tissue slide specimen that is the output of H&E slide staining.

**Comment by nhaubein** [comment]
This proposal appears accurate to me.

- Ned

ned.haubein@uphs.upenn.edu<mailto:ned.haubein@uphs.upenn.edu>
215-898-9574 (office)
215-776-2511 (work mobile)
Penn Medicine

**Comment by cstoeckert** [comment]
Propose making:
IHC stained fixed tissue slide specimen: a fixed tissue slide specimen that is generated during the process of immunohistochemistry.
Alternate label: immunohistochemistry slide specimen
Axiom: 'participates in' 'immunohistochemistry' 
Note that 'immunohistochemistry' is in OBI: http://purl.obolibrary.org/obo/OBI_0001986

**Comment by nhaubein** [comment]
This proposal appears accurate to me.

- Ned

ned.haubein@uphs.upenn.edu<mailto:ned.haubein@uphs.upenn.edu>
215-898-9574 (office)
215-776-2511 (work mobile)
Penn Medicine

**Comment by cstoeckert** [comment]
discussed on 12/1 OBIB call. Creating a IHC staining process to specify stained specimen as output was proposed.

**Comment by cstoeckert** [comment]
These have been submitted to OBI. See https://sourceforge.net/p/obi/obi-terms/825/

**Comment by cstoeckert** [comment]
discussed on 12/12 OBI call. Approved for addition into OBI. I'll take care of that and then import into OBIB.

**Comment by cstoeckert** [comment]
THese have been added to OBI and will be imported into OBIB after the next OBI release

**Comment by cstoeckert** [comment]
These have been imported in OBIB for the next release.
