### ISSUE TITLE
study and consent terms submitted by Duke (HJELLIS) for consideration. 

### ISSUE THREAD

**Issue by hjellis** [biobanking/biobanking#21]
https://docs.google.com/spreadsheets/d/14vNJi2GVTytW_cRW0RZOq4qKsupYoelQ8A3uPux0VaM/edit#gid=0

these are study and consent related terms from the terminology effort at Duke

**Comment by hjellis** [comment]
Chris I think we need to address these terms and get them into ICO. Perhaps prioritizing the ones that have a clear parallel in GTEx. What do you think?

**Comment by cstoeckert** [comment]
taken care of by ICO now
