### ISSUE TITLE
specimen integrity, specimen laterality specimen weight,  and  specimen size  

### ISSUE THREAD

**Issue by masciam** [biobanking/biobanking#24]
This terms has been discussed during the OBIB call on March 30th 2017 
My proposed definitions are:
Specimen integrity : wholeness and inheres in some specimen
Specimen laterality : Laterality and inhere in some specimen?
Specimen weight : equivalent to specimen weigh measurement (http://purl.obolibrary.org/obo/IAO_0000414)?
Specimen size: equivalent to specimen measurement  ( http://purl.obolibrary.org/obo/OMIABIS_0001038)?

**Comment by cstoeckert** [comment]
Is specimen laterality different from anatomical laterality (http://purl.obolibrary.org/obo/FMA_52549)?

**Comment by hjellis** [comment]
consider Duke and Penn terms, i feel its important to model both organs with 2 parts (e.g. left and right lung) and within an organ (left and right lobe of thyroid) we should ask Shannon McCall if those 2 examples are considered 'laterality'. We should also check if BBRB has a similar term @cstoeckert .

**Comment by zhengj2007** [comment]
Something like left lung and right lung are available in UBERON.

left lung
http://purl.obolibrary.org/obo/UBERON_0002168
right lung
http://purl.obolibrary.org/obo/UBERON_0002167

**Comment by cstoeckert** [comment]
Indeed. left lung is in OBIB. And we have added terms like ‘left lung biopsy'
Chris

**Comment by cstoeckert** [comment]
discussed on OBIB July 27, 2017
will investigate Uberon (look for mapping to FMA: anatomical laterality) and then add terms such as those identified by Duke and Penn biobanks.

Agree that specimen size is specimen measurement

specimen weight: a mass measurement datum that is about some specimen.

wholeness: http://purl.obolibrary.org/obo/PATO_0001442
specimen wholeness: A wholeness quality inhering in a specimen.

**Comment by cstoeckert** [comment]
Looked further into laterality. Problem with FMA 'anatomical laterality' is that there is not definition. Uberon just covers physical entities (e.g. left lung) but not relations (e.g., left). 
PATO has 'position' http://purl.obolibrary.org/obo/PATO_0000140 with subclasses like 'left side of', 'bilateral', 'anterior', and many more. I propose importing PATO: position (a physical quality) and using it to make 'specimen position' with alternative label 'specimen laterality'.
Definition: A position inhering in a specimen.

**Comment by jobeid** [comment]
discussed on OBIB call today and decided to go with Position in PATO. (Left side of, Right side of)

**Comment by cstoeckert** [comment]
Imported needed PATO terms and added specimen weight, specimen integrity, and specimen position.
https://github.com/biobanking/ontology/commit/af784303ed985425589cb58cbaa4ee0e12ac5f9f
@masciam please review these in obib_dev.owl and close issue if OK.

**Comment by cstoeckert** [comment]
Closing based on comment on commit.
