### ISSUE TITLE
Create class "biobank description"

### ISSUE THREAD

**Issue by mbrochhausen** [biobanking/biobanking#26]
Superclass: textual entity
Definition: "A textual entity providing information about a biobank in English."
SuperClass: 'is about' some biobank

**Comment by cstoeckert** [comment]
sounds good

**Comment by zhengj2007** [comment]
Is it too specific? If I have some description of biobank is in Chinese, or German, it is not biobank description based on the definition.

**Comment by mbrochhausen** [comment]
It is not according to the textual definition. Please keep in mind that the axiom is a necessary axiom, not a necessary and sufficient axiom, so we are not claiming to provide a formal (axiomatic) definition. We might want to think about changing the label to "biobank description in english".

**Comment by mbrochhausen** [comment]
Done. https://github.com/biobanking/ontology/commit/c11e2db324c4ed4da61473f8db27373aae7185fd
