### ISSUE TITLE
Obsolete OMIABIS_0000006 "sample collection or study identifier" and replace with 2 classes

### ISSUE THREAD

**Issue by mbrochhausen** [biobanking/biobanking#27]
**Step 1:** Obsolete "sample collection or study identifier"
**Step 2:** Create new class "sample collection identifier; Superclass: 'proper name'; definition: "A proper name that is centrally registered and unique within one framework and that refers to a sample collection."; SubClassOf: 'proper name'
 and (designates some 
    ('object aggregate' and ('has part' only specimen)))
**Step 3:** Create new class "study identifier; Superclass: 'proper name'; definition: "A proper name that is centrally registered and unique within one framework and that refers to study design execution."; SubClassOf: 'proper name'
 and (designates some 'study design execution)

**Comment by cstoeckert** [comment]
I think is definitely an improvement to split these. How does a centrally registered 'study identifier' relate to a 'centrally registered identifier' (CRID)?

**Comment by mbrochhausen** [comment]
I think this reflects an old rift between Alan Ruttenberg and me. For MIABIS we do not need the CRID aspect, so being pragmatic, I'd say let's change the textual definitions as follows: "A proper name that refers to a sample collection." and "A proper name that is centrally registered and unique within one framework and that refers to study design execution." respectively.

**Comment by cstoeckert** [comment]
The change in 'sample collection identifier' textual definition works for me. Can we also apply that textual definition approach to the 'study identifier' to distinguish it from a CRID?

**Comment by mbrochhausen** [comment]
Yes, absolutely.

**Comment by mbrochhausen** [comment]
I will not create a class 'study identifier' since that already exists.http://purl.obolibrary.org/obo/OMIABIS_0000037.

Also, I decided the make the axiom an equivalent axiom instead of a subClassOf axiom in parallel to all the other identifiers (biobank, study).

**Comment by mbrochhausen** [comment]
PS: The axiom on 'sample collection identifier' is what I am talking about in my last comment.

**Comment by mbrochhausen** [comment]
Done:
https://github.com/biobanking/ontology/commit/57ef42e7be1d1429573f45c0fba0f09210ff4736
https://github.com/biobanking/ontology/commit/2cbcd5eb4864ef0a934c1d062c8e5bf8bcc5be7c 
Please review my last two comments and close.

**Comment by mbrochhausen** [comment]
Closed after curator agreement.
