### ISSUE TITLE
Need to MIREOT http://purl.obolibrary.org/obo/OBI_0500027 'eligibility criterion'

### ISSUE THREAD

**Issue by mbrochhausen** [biobanking/biobanking#28]
We need this for MIABIS. Since I use a different MIREOT methodology, maybe Jie could take care of this?

Many thanks,
Mathias

**Comment by zhengj2007** [comment]
@mbrochhausen @cstoeckert 
I will work on it with Chris since I think he needs more terms from OBI too.

**Comment by mbrochhausen** [comment]
Great! Thanks.

**Comment by cstoeckert** [comment]
we have  http://purl.obolibrary.org/obo/OBI_0500026 eligibility criterion.
did you mean 'inclusion criterion'? I can add to the current list of imports I'm working on.

**Comment by mbrochhausen** [comment]
Yes, I did mean inclusion criterion!

**Comment by cstoeckert** [comment]
Done as part of BBRB commits
a2ecd2b8ed3c95303d62ee42087b24e68c36e3b6
6171ab47c98a0612138e67094394bb938828a4b2
