### ISSUE TITLE
Definition of "count"

### ISSUE THREAD

**Issue by mbrochhausen** [biobanking/biobanking#29]
I realized yesterday that OBIB picked up a wrong/no longer up-to-date definition of count. The definition should be what is found in Apollo-SV through OntoBee:
http://www.ontobee.org/ontology/APOLLO_SV?iri=http://purl.obolibrary.org/obo/APOLLO_SV_00000032
I am not sure how we want to go about this. Do we want to re-import the class?

**Comment by mbrochhausen** [comment]
1. Ok, we should do that.
2. That is a good question. I think that the OBI community is a little ahead of the OBI OWL file there. If you look at the examples of usage for assay in OBI you will find "Assay the wavelength of light emitted by excited Neon atoms. **Count of geese flying over a house**." (bold added by me). That statement was the reason why I put "count" under data item. I would also hold that "count" fulfills the definition of data item "a data item is an information content entity that is intended to be a truthful statement about something (modulo, e.g., measurement precision or other systematic errors) and is constructed/acquired by a method which reliably tends to produce (approximately) truthful statements." A count is intended to be a truthful statement and it is produced using a method (assigning a natural number to each individual that is counted not leaving out a single natural number) which reliably tends to produce truthful statements.
3. I think it is not. STATO requires that it is an integer (s. the definition in STATO). I would hold that "five" is a count, if someone asked me for the number of fingers on my right hand.

**Comment by zhengj2007** [comment]
Thanks @mbrochhausen

**Comment by cstoeckert** [comment]
>  Count of geese flying over a house.
This was discussed at the time of defining assay in OBI and put in to indicate it was a type of assay as we defined it. 
Chris
