### ISSUE TITLE
import more terms from external resources

### ISSUE THREAD

**Issue by zhengj2007** [biobanking/biobanking#3]
import following classes from EFO:
  http://www.ebi.ac.uk/efo/EFO_0001799 #ethnic group
  http://www.ebi.ac.uk/efo/EFO_0004950 #date of birth

Import following relations from RO
  http://purl.obolibrary.org/obo/RO_0002180 #has component
  http://purl.obolibrary.org/obo/BFO_0000063 #precedes
  http://purl.obolibrary.org/obo/BFO_0000062 #preceded by

The terms are needed for representation of Penn biobanking data

**Comment by cstoeckert** [comment]
These have been imported so am closing this issue
