### ISSUE TITLE
NTR: specimen collection related terms from NCI BBRB

### ISSUE THREAD

**Issue by cstoeckert** [biobanking/biobanking#35]
The first batch of terms needed to add on behalf of the Leidos/NCI BBRB project is listed on this google sheet:
https://docs.google.com/spreadsheets/d/1bHzUmryOLUjZJ4G0fwFNaUJoMBV72zZGNa_zX56mfrw/edit#gid=0
These are related to specimen collection and cover the processes and data items associated with preparing and monitoring the donor, removing the specimen, and initial tracking and preparation of the specimen. Some related terms have been submitted to other ontologies such as OBI, DO, and OGMS.
https://github.com/obi-ontology/obi/issues/823
https://github.com/obi-ontology/obi/issues/824
https://github.com/obi-ontology/obi/issues/825
https://github.com/obi-ontology/obi/issues/834
https://github.com/obi-ontology/obi/issues/835
https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/317
https://github.com/OGMS/ogms/issues/112

**Comment by hjellis** [comment]
Chris this represents a lot of great work. I've made only a few comments using the comment tool, and highlighting the cell in yellow.

**Comment by cstoeckert** [comment]
Added via import_BBRB.owl file in import folder
https://github.com/biobanking/ontology/commit/8f15d93ba105b042eebbf49e2c80277585fc851b
