### ISSUE TITLE
http://purl.obolibrary.org/obo/IAO_0020000 has two labels

### ISSUE THREAD

**Issue by cstoeckert** [biobanking/biobanking#38]
Has label 'identifier' and has label 'proper name'
Let's choose one and make other alternative label.
@mbrochhausen

**Comment by mbrochhausen** [comment]
resolved: https://github.com/biobanking/biobanking/commit/17c9770973e8546ab2df614bb3221cbcae10b4b1

**Comment by mbrochhausen** [comment]
I thought I solved it. Maybe Jie can check what I did to the repo.
Maybe it is also an import issue? PNO is correct and doesn't have the double label.

**Comment by zhengj2007** [comment]
@mbrochhausen You changed the code in biobanking repository. Current we have moved the source code in ontology repository (https://github.com/biobanking/ontology).

I updated page, https://github.com/biobanking/biobanking, and specified that ontology source code located in another repository.
