### ISSUE TITLE
new terms related to research authorization process for post mortem specimen donation 

### ISSUE THREAD

**Issue by hjellis** [biobanking/biobanking#40]
Updated worksheet, ready for comment and then submission to OBIB

https://docs.google.com/spreadsheets/d/1p0Gtq3Id_xlJ8SFmeCGqLP-woBxhP28UFAGl7Yg363w/edit#gid=0

**Comment by hjellis** [comment]
Chris pointed out- 
specimen donor's date of birth | a date of birth that signifies the calendar date on which a particular donor of a specimen was born |   should have this as a parent  | consent_795: CS - use http://www.ebi.ac.uk/efo/EFO_0004950 as parent |

**Comment by hjellis** [comment]
entire worksheet can be found here. 
https://docs.google.com/spreadsheets/d/1p0Gtq3Id_xlJ8SFmeCGqLP-woBxhP28UFAGl7Yg363w/edit?ts=59838107#gid=0

**Comment by fjmanion** [comment]
Specific terms:
For "identification number of a protocol at a particular site" should this be modeled as a 'centrally registered identifier' - see IAO_0000578?

For "relationship between person signing research authorization and specimen donor", I'm assuming this is from ERO_0002033?

I've also attached my copy of the spreadsheet with comments added for your convenience. It has all notes for tracker items 39, 40, and 41. Unfortunately, it's an Excel file...
[Consent form BBRB.xlsx](https://github.com/biobanking/biobanking/files/1271405/Consent.form.BBRB.xlsx)

**Comment by cstoeckert** [comment]
Added as part of https://github.com/biobanking/ontology/commit/b95d7d6ca0d91dfc04b8beab14b9fd3390717e71
now in OBIB release 2017-10-12
