### ISSUE TITLE
NTR: NCI BBRB terms related to specimen transport, handling and preparation

### ISSUE THREAD

**Issue by cstoeckert** [biobanking/biobanking#42]
Propose adding 125 terms listed in the BBRB processing storage and handling ROBOT file at:
https://docs.google.com/spreadsheets/d/1bIC93C_3q4UU72TP1Bfejvuet639erGalmGnGsye35s/edit?usp=sharing
I've marked in green terms that might first go to OBI.
Initially will just put in with textual definitions but the last column indicates potential logical axioms to add later.

**Comment by zhengj2007** [comment]
Terms were added
https://github.com/biobanking/ontology/blob/fae71670d36f363498b7d983cf87bf15ae84a46d/src/imports/import_BBRB.owl

**Comment by zhengj2007** [comment]
Terms were added 
https://github.com/biobanking/ontology/commit/fae71670d36f363498b7d983cf87bf15ae84a46d
