### ISSUE TITLE
Eligibility criteria to add to OBIB

### ISSUE THREAD

**Issue by hjellis** [biobanking/biobanking#45]
see spreadsheet https://docs.google.com/spreadsheets/d/1OxHwvOijXrtJiCu3fK45sTWNnBcbRqgSqUZpuY_klpU/edit#gid=1233805461
Note that column A defines whether term should go in OBIB vs OBI

**Comment by cstoeckert** [comment]
OBIB terms have been added as part of https://github.com/biobanking/ontology/commit/b95d7d6ca0d91dfc04b8beab14b9fd3390717e71
OBI requested terms still to be added

**Comment by cstoeckert** [comment]
OBI terms have been added in this commit:
biobanking/ontology@0c49cc9
