### ISSUE TITLE
Clinical History and related terms for OBIB consideration

### ISSUE THREAD

**Issue by hjellis** [biobanking/biobanking#47]
Here is a link to the google document. Please review prior to our call on 9-27, if possible. 

https://docs.google.com/spreadsheets/d/1nbibtBM_4QD_o4mSu1IAxCZKFiChZ6d1AIWcTaGS5GI/edit#gid=0

**Comment by cstoeckert** [comment]
Added as part of https://github.com/biobanking/ontology/commit/b95d7d6ca0d91dfc04b8beab14b9fd3390717e71
Now in OBIB 2017-10-12 release
