### ISSUE TITLE
NTR: more NCI BBRB terms equested

### ISSUE THREAD

**Issue by cstoeckert** [biobanking/biobanking#48]
These are the remaining terms proposed to be added directly to OBIB.

Tissue specimen suitability for molecular analysis: A conclusion textual entity that signifies whether a specimen is acceptable for molecular analysis based on the assessment by a pathologist of a tissue specimen based on qualities such as purity and size. 

specimen gross appearance of metastatic tumor: A specimen gross appearance of a tumor that has spread from its original site by discontinuous (not direct) spread, e.g. by blood or lymphatics.

specimen gross appearance of tumor center: A specimen gross appearance of the most internal topographic location of the tumor.

specimen gross appearance of tumor edge: A specimen gross appearance of the border of the tumor with non-tumorous tissue.

research authorization for post mortem specimen donation for a specific tissue or fluid: A research authorizationi documentation for postmorten specimen donation in which the authorization is for a specified tissue or biological fluid.

**Comment by hjellis** [comment]
these look good

**Comment by cstoeckert** [comment]
manually added to OBIB:
https://github.com/biobanking/ontology/commit/ff9684ba8228d044f7ada2bbe691815e1ed87604
https://github.com/biobanking/ontology/commit/8a8adb9962041f606b2e98175ce2aa41ba3f6cc8
