### ISSUE TITLE
OBIB "medication role" vs. DrO "clinical drug role"

### ISSUE THREAD

**Issue by jcschule** [biobanking/biobanking#49]
Hi all,

I am a Biomedical Informatics PhD student in Buffalo working under the guidance of Drs. Barry Smith and Werner Ceusters on a project as part of their Advanced Ontology class.

I have an issue regarding 2 ontologies which are closely related: the Ontology for Biobanking and the Drug Ontology.

The OBIB includes a term, "medication role," with corresponding definition, "A role borne by some material entity which can be delivered/administrated into some organism and the role is realized during a clinical treatment process aiming to treat symptoms, signs or diagnosed disease." (http://purl.obolibrary.org/obo/OBIB_0000026)

Similarly, the DrO includes a term, "clinical drug role," with definition, "The role of a material entity to prevent, diagnose, treat, or study disease and/or its effects." (http://purl.obolibrary.org/obo/DRON_00000001)

These definitions are quite similar.

My goals of using one of these terms with a current and expanding project is, strictly speaking, more in line with the DrO, and so I have a preference toward using the term, "clinical drug role", and corresponding subtype, "FDA approved drug role," however, the OBIB definition is slightly more complete, describing when the role is realized. 

One issue I have with the OBIB definition is the claim to treat **diagnosed** disease. I claim one can treat a disease without having reached a formal diagnosis. For example, I am treating some pain in my leg with aspirin. What I don't know, as this is the first time experiencing such pain and I have not yet sought medical help, is the disease causing me pain is osteosarcoma. Nevertheless, I believe one of these roles is inhering in the aspirin, as it is treating a sign, symptom, or effect of the disease.

Returning to the original issue, perhaps these should be collapsed into 1 term and 1 definition, with 1 ontology referring to the other? Or, if they truly are different, an expansion of both definitions to delineate between the 2 would be helpful.

Kind regards,

Jim

**Comment by cstoeckert** [comment]
Jim,
Thanks for your interest in OBIB! Medication role would include clinical drug role but extend beyond what I would think of as a clinical drug. For example we have encountered use of activated charcoal and blood transfusions as medications which I don't think of as clinical drugs. For the OBIB definition, note that it is not only diagnosed disease (i.e., "symptoms, signs, OR diagnosed disease" not OF diagnosed disease.
Chris
