### ISSUE TITLE
Storage related terms from Duke

### ISSUE THREAD

**Issue by cstoeckert** [biobanking/biobanking#5]
These were discussed on the Nov. 19, 2015 Biobanking call. 

Container: similar to OBI_0000967 ‘container’ but the Duke term has additional requirement of touching a sample.
The relevant (planned) process is ‘adding specimen into a container’ http://purl.obolibrary.org/obo/OBIB_0000034
Proposed term: ‘specimen container’
Definition: A container that is used to store specimens.
Parent term: container
Logical axiom: container and is_specified_output of some ‘adding a specimen into a container'

Container type: these are subtypes of OBI ‘container’
e.g., OBIB_0000031 cryovial; OBIB_0000032 vacutainer
Can also add the following but will need help with definitions for them (except conical tube):
    ‘conical tube’
    ‘Copan e-Swab’
    ‘CPT Vacutainer’
    ‘Paxgene DNA’
    ‘Paxgene RNA’
    ‘Salivettes'
    ‘specimen cup’
    ‘SST vacutainer’
    ‘sterile cup'
Many Duke terms have associated maximum volumes. These can be added and defined like the following:
    ‘0.5 ml cryovial’: cryovial and has maximum capacity 0.5 ml

Storage unit: similar to OBI_0000967 ‘container’ but the Duke term may have additional requirement of associated layouts. 
The relevant (planned) process is ‘storage’ http://purl.obolibrary.org/obo/OBI_0302893
Can either just use OBI ‘container or create a subclass of container: 
‘storage container’ with definition: container and participates in some storage 

Physical store: a type of Duke storage unit with specific attributes. Has the same examples (freezer, box) so not clear what are those specific attributes and how they will be used. 

Storage unit ID: related to ’specimen identifier’ IAO_0001616. Is this sufficient or do we need the following?  
Proposed term: ‘storage container identifier’
Definition: a CRID symbol denoting the contents of storage container.

Storage unit name: related to ‘proper name’ IAO_0020000.
Proposed term: ‘storage container name’
Definition: a proper name that identifies a storage container.

Storage unit type: subclasses of proposed ‘storage container’
    freezer see ‘freezer’ ERO_0000979
    rack see ‘freezer rack’ OBIB_0000015
    shelf see ‘freezer shelf’ OBIB_0000010
Need help on how these are distinct from storage containers or containers in general.
    box 
    slot
also have specified box configurations that I need help with definitions:
    box-10x10 (units? slots?)
    box-9x9
    BoxPos

**Comment by zhengj2007** [comment]
Proposed term: ‘specimen container’
Definition: A container that is used to store specimens.
Parent term: container
Logical axiom: container and is_specified_output of some ‘adding a specimen into a container'

Should it be input of some ‘adding a specimen into a container'? I think the output is container + specimen.

Considering following proposed storage container. I think we may consider to create some new functions to make defined classes. A container can be both specimen container and storage container.

**Comment by zhengj2007** [comment]
Can we define 'box configurations' as ICE specification? similar as 'dose specification'

**Comment by cstoeckert** [comment]
Discussion on Dec. 3 call. 
Specimen container: create a function to contain specimens. change wording to indicate it is to be used for containing specimens
We can add subtypes of specimen containers with associated volumes but not immediate priority
Storage unit is equivalent to OBI container
Physical store is a OBI container with environmental control function.

**Comment by cstoeckert** [comment]
Proposed definitions for types of specimen containers. 
These are based on looking them up on-line with sources indicated:
COPAN eSwab: a specimen container that is a liquid-based multipurpose collection and transport system that maintains viability of aerobic, anaerobic and fastidious bacteria. source: http://www.copanusa.com/products/collection-transport/eswab/

CPT (Cell Preparation Tube) Vacutainer: a specimen container that is an evacuated Tube with Sodium Heparin intended for the collection of whole blood and the separation of mononuclear cells. source: https://www.bd.com/vacutainer/pdfs/bd_cpt_VDP40105.pdf

The PAXgene Blood DNA Tube: a specimen container that is intended for the collection of whole blood for genomic DNA isolation. source : http://www.preanalytix.com/products/blood/dna/paxgene-blood-dna-tube-761115

The PAXgene™ Blood RNA tube: a specimen container that is part of a system that standardizes and integrates the key steps of whole blood collection, nucleic acid stabilization, and RNA purification.  source: https://us.vwr.com/store/catalog/product.jsp?product_id=4646732

The Salivette saliva collection device: a specimen container that contains a sterile cotton swab, label, and exterior tube for collection of saliva samples prior to assay. source: https://www.alpco.com/store/salivettes-sterile-saliva-collection-devices.html

SST Vacutainer: a specimen container that is a serum separator tube used in medical clinical chemistry tests requiring blood serum. They contain a special gel that separates blood cells from serum, as well as particles to cause blood to clot quickly. source: https://en.wikipedia.org/wiki/Serum-separating_tube

These are just based on guesses so edits for improvements appreciated:
specimen conical tube: a specimen container that is a tube with a conical bottom which is useful for concentrating pellets.

specimen cup: a specimen container that is cup shaped typically with a lid.

sterile specimen cup: a specimen cup that has been previously sterilized.

**Comment by masciam** [comment]
CPT (Cell Preparation Tube) Vacutainer: a specimen container that is an evacuated Tube with Sodium Heparin intended for the collection of whole blood and the separation of mononuclear cells. can be either Sodium Heparin or Sodium citrate. source: http://www.bd.com/vacutainer/products/molecular/citrate/
CPT should be a child of vacutainer in OBI http://purl.obolibrary.org/obo/OBI_0000832.
I have a question about vacutainer in OBI is a child of test tube  http://purl.obolibrary.org/obo/OBI_0000836 and test tube is defined as been open at the top, does this go in conflict with the vacutainer that in order to have a vacum inside needs to be closed?

The PAXgene Blood DNA Tube and The PAXgene™ Blood RNA tube
to define these special type of tubes I think we can use their final purpose so are containers that not only have the contain function but are used for specific processes such as the DNA  extraction http://purl.obolibrary.org/obo/OBI_0000257 or total RNA extraction   http://purl.obolibrary.org/obo/OBI_0000855
Could they have a material separation function? http://purl.obolibrary.org/obo/OBI_0000372 or we can create a more specific RNA and DNA separation function child of material separation function.
Another possibility is consider these tubes as material separation instrument http://purl.obolibrary.org/obo/ERO_0000624 ed specifically DNA extraction/purification instrument http://purl.obolibrary.org/obo/OBI_0001114
and RNA extraction /purification instrument http://purl.obolibrary.org/obo/OBI_0001050

**Comment by cstoeckert** [comment]
Thanks for the feedback!

regarding vacationer as a child of test tube. That is actually in OBIB (http://purl.obolibrary.org/obo/OBIB_0000032) not OBI so something we can go ahead and fix if we all agree.

Regarding PAXgene tubes, I agree that they are used for other processes but as participants. Do we have a use case for them besides just knowing what specimen containers are available or used for collecting a specimen? That would help determine what additional axioms are needed.

**Comment by augustearth** [comment]
Do we have classes for "vacutainer" and "cryovial"?  Based on my experience, these are common terms used by people in bio-banking and would be useful to include in the hierarchy.

**Comment by cstoeckert** [comment]
Discussed on Jan. 14, 2016 call.
Agreed to:
Deprecate vacutainer from OBIB and add under specimen container in OBI. (will want to do the same for cryovial).
Add additional functions for containers built for specific purposes (AI: Anna Maria)
Volumes will be captured as a container property and not used to generate subtypes. 
Pretreated tubes will have an additive property but also need to capture untreated tubes where additive is added with specimen.

To Do:
Duke and BBRB review list of terms and add others as needed. 
Think about how to capture specimen type when specific for a container type.

**Comment by hjellis** [comment]
duke sample containers
‘conical tube’

'Vacutainer’
SST Vacutainer
‘Paxgene DNA’
‘Paxgene RNA’
‘specimen cup’
‘sterile cup'
filter paper
Guthrie card
Cryo vial
Conical Tube
Multiwell plate

**Comment by masciam** [comment]
Here are my suggestions for the PAXGene tubes:
PAXgene Blood DNA Tube is a vacutainer that has function some "DNA separation function" and realized in only  DNA extraction process
DNA separation function is a material separation function
PAXGene Blood DNA tube we still need to address the fact that is only for blood  should we have a blood vacutainer?
PAXgene Blood RNA Tube is a vacutainer that has function some "RNA separation function" and realized in only  RNA extraction process.

DNA extraction http://purl.obolibrary.org/obo/OBI_0000257
RNA extraction http://purl.obolibrary.org/obo/OBI_0666666
material separation function http://purl.obolibrary.org/obo/OBI_0000372
DNA separation function new function
RNA separation function new function

**Comment by masciam** [comment]
my comments for TMA:
Cylindrical cores are obtained from a number (up to 1,000) of individual formalin-fixed,
paraffin-embedded tissue blocks. These are transferred to a
recipient TMA block. I think a tissue microarray block  is a container  of the paraffine tissue block,
 the paraffine block is not limited the location is just conserving the specimen

**Comment by cstoeckert** [comment]
Discussed on Jan 28, 2016 call.
Will continue to use this tracker to collect container terms but need another mechanism to organize and define them. Will start with a spreadsheet of google doc but will also look into WebProtege.
To organize container terms, consider the processing of the containers and the specimens.
There are containers that are general (tubes, slides) that are used also for specimens.
There are containers that are treated in some way for specimens (with additives like EDTA).
And there are specially designed containers for specimens (Paxgene tubes). 
Discussed case of specimens in paraffin blocks that are in cassettes. Recognized additional requirement of specimen containers to allow for identifiability of specimen (can be labeled). This make the cassette the specimen container and not the paraffin block.

**Comment by cstoeckert** [comment]
I've started a google spreadsheet here: 
https://docs.google.com/spreadsheets/d/1IIV0SMBbv1h_vonq-wsgzL230DC4RrUoWx6m6KWqILk/edit?usp=sharing
If you want to edit, let me know with the email you want to use and I'll add you.

**Comment by zhengj2007** [comment]
About paraffin tissue block, worth to look at related term in OBI: paraffin specimen
http://purl.obolibrary.org/obo/OBI_0000950
A specimen that is output of a paraffin storage process in which specimen is embedded in paraffin.

**Comment by cstoeckert** [comment]
Nice, thanks Jie! This is consistent with our discussion.

**Comment by cstoeckert** [comment]
Moved cryovial and vacutainer to be directly under container. Will deprecate once these are in OBI and we can import.

**Comment by cstoeckert** [comment]
imported from OBI: 'specimen container' and associated 'containing a specimen function', 'physical store'

**Comment by fkhanBBRB** [comment]
Based on our comparison, below are some additional container types listed in caHUB along with their definitions:

- ACD Yellow Top – ACD Yellow Top Tube
- GTEx Aqua Kit Fixative – The type of container or fixative the specimen is placed into upon collection via the GTEx aqua kit
- GTEx Yellow Kit Fixative/Container – The type of container or fixative the specimen is placed into upon collection via the GTEx yellow kit
- Lavender EDTA – Lavender EDTA

**Comment by hjellis** [comment]
I advise not using colors to define a container type . Colors vary by vendor. Also advise not using an proprietary names (e.g. GTEx). Can you define the types of container (e.g. vacutainer) and preservative (ACD= Acid Citrate Dextrose)

**Comment by cstoeckert** [comment]
These two at least are now in OBIB:
‘Paxgene DNA Vacutainer’ | http://purl.obolibrary.org/obo/OBIB_0000234
‘Paxgene RNA Vacutainer’ | http://purl.obolibrary.org/obo/OBIB_0000235

**Comment by cstoeckert** [comment]
No longer an issue now
