### ISSUE TITLE
two IRIs for 'addition of molecular label'

### ISSUE THREAD

**Issue by cstoeckert** [biobanking/biobanking#51]
Seem to be the same term:
http://purl.obolibrary.org/obo/OMIABIS_0000912
http://purl.obolibrary.org/obo/OBI_0600038

**Comment by mbrochhausen** [comment]
Indeed. That is a bit of a surprise. It should have the OBI URI for sure.
Probably the OMIABIS URI was created by accident. Can we merge them in a
way that for the users of the OMIABIS URI things remains traceable?

**Comment by cstoeckert** [comment]
How about if we obsolete the OMIABIS term and add the annotation http://purl.obolibrary.org/obo/IAO_0100001 'term replaced by' and point to the OBI term?

**Comment by mbrochhausen** [comment]
Agreed

**Comment by cstoeckert** [comment]
Fixed. f10951b81942cf7e489d8193d15e61787ea3f628
