### ISSUE TITLE
NTR: FFPE specimen

### ISSUE THREAD

**Issue by sjbost** [biobanking/biobanking#55]
1. editor preferred term: FFPE specimen
2. alternative terms: formalin-fixed paraffin-embeded specimen
3. A specimen that has been fixed in formalin and embedded in paraffin.
4. https://www.biochain.com/general/what-is-ffpe-tissue/
5. subclass of paraffin specimen
6. An FFPE specimen used in oncology
7. MIABIS

**Comment by sjbost** [comment]
Requested as OBI issue #1019

**Comment by cstoeckert** [comment]
imported from OBI https://github.com/biobanking/ontology/commit/4ff220929264075b9f152fdb2b894f450761c445
