### ISSUE TITLE
NTR: genealogical record

### ISSUE THREAD

**Issue by sjbost** [biobanking/biobanking#56]
1. editor preferred term: genealogical record
2. alternative terms: none
3. textual definition: A document about the family relationships of persons related as members of a domestic group linked through a descent from a common ancestor, marriage, or adoption.
4. source: Adaptation of 'family relationship' in eagle-i resource ontology
5. subclass of 'document;' is about some family relationship
6. example of usage: A family tree is a type of genealogical record.
7. term editor: MIABIS

**Comment by mbrochhausen** [comment]
I think that this is a good definition for genealogical record in general, but I am wondering whether what MIABIS has in my is more of a medical genealogy where we just look at biological relationships and not at social relationships (adoption). This is something we should describe with the whole group, maybe.

**Comment by mbrochhausen** [comment]
After a conversation with the domain experts we decided to go forward with the definition that Sarah proposed. We also decided that this term should be added to OBI and imported to OBIB. Sarah will create an OBI issue tracker item. We will keep this issue tracker item open until the import is done.

**Comment by sjbost** [comment]
Requested as OBI issue #1023

**Comment by sjbost** [comment]
Resolved with https://github.com/biobanking/ontology/commit/e66fa00d0bf902aa2481752e322ac1a07bc8abb3
