### ISSUE TITLE
Parent of FMA:Anatomical location in OBIB

### ISSUE THREAD

**Issue by zhengj2007** [biobanking/biobanking#59]
FMA:Anatomical location (http://purl.obolibrary.org/obo/FMA_50707) was imported as a subClass of BFO:continuant (http://purl.obolibrary.org/obo/BFO_0000002). Should it be BFO:independent continuant or BFO:immaterial entity?

**Comment by cstoeckert** [comment]
Since Anatomical location is a FMA:Non-physical anatomical entity, I think that it could be imported under BFO:immaterial entity.

**Comment by cstoeckert** [comment]
Discussed on OBIB call July 11, 2019. Agree with moving under immaterial entity.
