### ISSUE TITLE
Improve definition of 'patient questionnaire'

### ISSUE THREAD

**Issue by cstoeckert** [biobanking/biobanking#60]
The definition was cited in "Guidelines for writing definitions in ontologies" Seppala et al 2017 as an example to avoid of lists and etc. They recommend: "patient questionnaire: A questionnaire that comprises a set of demographic and medical questions, which will be filled by the human subject."

**Comment by cstoeckert** [comment]
Discussed on Aug 29, 2019 OBIB call: current defn is "A questionnaire that comprises a set of questions about a patient, such as height, weight, race, biological sex, clinical history, etc., which will be filled by the human subject." Want to improve but not lose that it is about a patient. Want to think about whether demographic and medical questions sufficiently covers what's now in a patient questionnaire.

**Comment by lizumberfield** [comment]
Proposed revision: 
Patient questionnaire: A questionnaire that comprises a set of demographic and medical questions for assessment, diagnostic, or therapeutic purposes, which will be filled by the human subject or their legally authorized representative.

Or label change:
- Specimen Contributor (Donor) Questionnaire

**Comment by lizumberfield** [comment]
Another proposed revision:
A questionnaire that comprises a set of questions for clinical or research purposes, which will be filled by the human subject or their legally authorized representative.

**Comment by cstoeckert** [comment]
Proposed revision:
Patient questionnaire: A questionnaire that comprises a set of demographic and medical questions  about a patient which will be filled by the human subject or their legally authorized representative.

**Comment by cstoeckert** [comment]
Done https://github.com/biobanking/ontology/commit/698b3a19fb4d7fd8c3036b3370db55f2e6e44530
