### ISSUE TITLE
Missing ontology scope

### ISSUE THREAD

**Issue by zhengj2007** [biobanking/biobanking#65]
According to OBO Foundry [principle 5](http://obofoundry.org/principles/fp-005-delineated-content.html), we should specify the scope of the OBIB ontology. 

OBO Foundry principle 5: "The scope of an ontology is the extent of the domain or subject matter it intends to cover. The ontology must have a clearly specified scope and content that adheres to that scope."

Any suggestion on it?

**Comment by cstoeckert** [comment]
biobanking
specimens

**Comment by mbrochhausen** [comment]
bio-repository
biocuration

**Comment by zhengj2007** [comment]
Added in the registration file and showed on the OBO Foundry OBIB homepage.
