### ISSUE TITLE
Duplicate exact synonym terms

### ISSUE THREAD

**Issue by zhengj2007** [biobanking/biobanking#67]
A couple of terms shared alternative labels, need to check anything wrong and fix the issues.

Term Label [ID] | Alternative Term
-- | -- 
authorization not obtained for whole brain donation [OBIB:0000493]  | tissue use limitations 
limitations on research authorization for use of donated specimens [OBIB:0000494] | tissue use limitations 
name of submitter of pathology case summary report. [OBIB:0000387] | name of submitting pathologist |  
name of reviewer of pathology case summary report. [OBIB:0000389] | name of submitting pathologist

The issues are identified by OBO Dashboard.
[OBIB dashboard report](http://obo-dashboard-test.ontodev.com/obib/robot_report.html)

**Comment by cstoeckert** [comment]
removed alternative term from OBIB:0000493
changed alternative term to 'name of reviewing pathologist' for OBIB:0000389
in branch robotissues

**Comment by cstoeckert** [comment]
https://github.com/biobanking/ontology/pull/2/commits/5e036d71a1b41d7c57c6d1c54a83e88bd402aa16
