### ISSUE TITLE
OBIB:0000517 preoperative performance status score with alternative term same as term label

### ISSUE THREAD

**Issue by zhengj2007** [biobanking/biobanking#68]
OBIB:0000517 preoperative performance status score 
alternative term: preoperative performance status score

Consider to remove.

**Comment by cstoeckert** [comment]
Agree

**Comment by cstoeckert** [comment]
Done on branch robotissues

**Comment by cstoeckert** [comment]
https://github.com/biobanking/ontology/pull/2/commits/5e036d71a1b41d7c57c6d1c54a83e88bd402aa16
