### ISSUE TITLE
Term definitions start with lowercase

### ISSUE THREAD

**Issue by zhengj2007** [biobanking/biobanking#69]
Term Label [ID] | Definition
-- | -- 
Location below resection [OBIB:0000058] | an anatomical location that is just below (1 cm) the site of surgery.  
Location adjacent to tissue fixation [OBIB:0000059] | an anatomical location that is adjacent to the site where tissue was collected and subjected to fixation. 
prosector role [OBIB:0000069] |  a role which inheres in a person and is realized in the dissection of a body for anatomical instruction or pathological examination. 
name of submitter of pathology case summary report. [OBIB:0000387] | name of submitter of pathology case summary report.

Definitions of 4 terms start with lowercase. We can change to uppercase when we have time. 

Identified by OBO Dashboard.
[OBIB dashboard report](http://obo-dashboard-test.ontodev.com/obib/robot_report.html)

**Comment by cstoeckert** [comment]
Updated OBIB:0000387 definition to "A personal name that designates the person who was the submitter of a pathology case summary report."
Fixed the others.
In branch robotissues

**Comment by cstoeckert** [comment]
https://github.com/biobanking/ontology/pull/2/commits/5e036d71a1b41d7c57c6d1c54a83e88bd402aa16
