### ISSUE TITLE
Imported terms deprecated in the external ontologies

### ISSUE THREAD

**Issue by zhengj2007** [biobanking/biobanking#71]
I found some imported ethnic group terms deprecated in the external ontology, EFO.  I think we need to make some corresponding changes in OBIB.

<img width="279" alt="Screen Shot 2020-05-01 at 2 27 49 PM" src="https://user-images.githubusercontent.com/6249284/80831613-24c01480-8bb9-11ea-966e-dc3ac5ffd669.png">

**Comment by zhengj2007** [comment]
We may consider to replace these terms by 'ancestry category' (http://purl.obolibrary.org/obo/HANCESTRO_0004) and its subclasses.

Related tracker: https://github.com/IHCC-cohorts/GECKO/issues/9

**Comment by zhengj2007** [comment]
Comments from daniwelter: "The subclasses of EFO:ethnic group were deprecated when EFO moved to importing HANCESTRO classes instead. EFO:ethnic group itself was retained for legacy reasons but all deprecated subclasses were replaced with subclasses of HANCESTRO:ancestry category."

Shall we replace the deprecated terms by HANCESTRO ones too?

**Comment by cstoeckert** [comment]
Identified new obsolete terms to replace:
Replace OMRSE: obsolete identity datum and subclasses with OMRSE: social identity information content entity

**Comment by cstoeckert** [comment]
EFO obsolete term : HANCESTRO replacement
obsolete_African American : HANCESTRO_0568 African American
obsolete_American : HANCESTRO_0463 American
obsolete_Asian : HANCESTRO_0008 Asian
obsolete_Asian Indian : HANCESTRO_0487 Indian
obsolete_Chinese : HANCESTRO_0021 Chinese
obsolete_European-American : HANCESTRO_0590 European American
obsolete_Hispanic : HANCESTRO_0014 Hispanic or Latin American
obsolete_Japanese : HANCESTRO_0019 Japanese
obsolete_Latino : HANCESTRO_0014 Hispanic or Latin American 
ethnic group EFO_0001799 is not obsolete but I would replace it with HANCESTRO_0004 ancestry category
Note that in EFO, Hispanic and Latino have the same definition. In OBIB, Latino is under American. I would replace this with HANCESTRO_0014 and make the parent HANCESTRO_0004
