### ISSUE TITLE
post-office box number

### ISSUE THREAD

**Issue by sjbost** [biobanking/biobanking#73]
Per @mbrochhausen need to review if post-office box number should be a subclass of CRID.

**Comment by cstoeckert** [comment]
Discussed at OBIB Aug 6, 2020 call. Resolve that it is not a CRID and should be moved under Identifier. Reason is that alone, it can not identify uniquely a box as it is location dependent.

**Comment by cstoeckert** [comment]
Please see comment on https://github.com/biobanking/ontology/pull/9

**Comment by sjbost** [comment]
Fixed with https://github.com/biobanking/ontology/commit/b4f332593238fd30743cbeb66210e99215ff2bd4
