### ISSUE TITLE
Revised term request: survey data

### ISSUE THREAD

**Issue by dillerm** [biobanking/biobanking#74]
Revise definition to reflect what the parent class is.

Proposed definiton: A data item that contains the outcome of a survey.

**Comment by cstoeckert** [comment]
We can discuss at the next OBIB call on Aug 3.

**Comment by dillerm** [comment]
Hi @cstoeckert , apologies for missing this. When will the next meeting be?

**Comment by sjbost** [comment]
@dillerm The next OBIB call is Thursday, August 6 at 3:00. I can forward you the call details.

**Comment by cstoeckert** [comment]
Discussed on OBIB August 6, 2020. Agree to change definition to say "A data item" rather than a data set.

**Comment by sjbost** [comment]
Fixed with https://github.com/biobanking/ontology/commit/47f3d715ce0a0795e76899510278a2fd4d1992d4
