### ISSUE TITLE
Assign OMIABIS terms in OBIB with OBIB IRIs

### ISSUE THREAD

**Issue by zhengj2007** [biobanking/biobanking#81]
Discussed on May 13, 2021. We are going to assign OMIABIS terms in OBIB with OBIB IRIs. Otherwise, the IRIs of OMIABIS terms will be resolved to OMIABIS ontology that may be out-of-date. 

Need to check which annotation property to indicate these OMIABIS terms when we assign them with OBIB IDs.

**Comment by zhengj2007** [comment]
There are some deprecated terms with OMIABIS. 

ID | Label
-- | --
OMIABIS:0000912 | obsolete_addition of molecular label
OMIABIS:0000049 | obsolete_bone marrow specimen
OMIABIS:0001075 | obsolete_cerebrospinal fluid specimen
OMIABIS:0001076 | obsolete_faeces specimen
OMIABIS:0000026 | obsolete_postal code
OMIABIS:0001077 | obsolete_saliva specimen
OMIABIS:0000006 | obsolete_sample collection or study identifier
OMIABIS:0000100 | obsolete_study principle investigator or responsible
OMIABIS:0001003 | obsolete_survey data
OMIABIS:00001013 | obsolete_unknown state specimen data

How will we deal with these terms? Keep them as what they are now or remove them completely from OBIB?

**Comment by cstoeckert** [comment]
Proposal is to deprecate all OMIABIS terms in OBIB as obsolete and use 'term replaced by' annotation property to point to OBIB replacement.

**Comment by mbrochhausen** [comment]
+1

**Comment by zhengj2007** [comment]
OBI imported two OMIABIS terms.
OMIABIS_0000050 fixed tissue specimen
OMIABIS_0000052 fixed tissue slide specimen

May we ask OBI to assign the OBI IDs to them?

**Comment by cstoeckert** [comment]
Decide to assign OBIB IDs to these.
