### ISSUE TITLE
wrong IDs for some OBIB terms

### ISSUE THREAD

**Issue by zhengj2007** [biobanking/biobanking#84]
http://purl.obolibrary.org/obo/OBI_0002000 specimen position
http://purl.obolibrary.org/obo/OBI_0002001 specimen integrity
http://purl.obolibrary.org/obo/OBI_0002002 specimen weight
http://purl.obolibrary.org/obo/OBI_0002003 specimen slide ID
http://purl.obolibrary.org/obo/OBI_0002004 surgical cancer treatment
http://purl.obolibrary.org/obo/OBI_0002005 specimen gross appearance of metastatic tumor
http://purl.obolibrary.org/obo/OBI_0002006 specimen gross appearance of tumor center
http://purl.obolibrary.org/obo/OBI_0002007 specimen gross appearance of tumor edge
http://purl.obolibrary.org/obo/OBI_0002008 research authorization for post mortem specimen donation for a specific tissue or fluid
http://purl.obolibrary.org/obo/OBI_0002013 tissue specimen suitability for molecular analysis

For example, OBIB has term 'tissue specimen suitability for molecular analysis' with ID: OBI_0002013
http://www.ontobee.org/ontology/OBIB?iri=http://purl.obolibrary.org/obo/OBI_0002013

However, the label for http://purl.obolibrary.org/obo/OBI_0002013 is 'nCounter Human miRNA Expression array'. 

I think we need to give the terms with OBIB IDs.

**Comment by cstoeckert** [comment]
Agree that prefix should be OBIB
