### ISSUE TITLE
duplicate synonym

### ISSUE THREAD

**Issue by zhengj2007** [biobanking/biobanking#87]
OBIB:0000640 biobank location ISO 3166-1 alpha-2 code
OBIB:0000656 ISO 3166-1 alpha-2 code for biobank contact person
Both have same alternative term 'Biobank country code'. 

Alternative term does not seem correct for OBIB:0000656. 

@mbrochhausen Could you please check it? Thanks!

**Comment by mbrochhausen** [comment]
The alternative term for OBIB:0000656 should be deleted. I am not sure that we need an alternative term. This is really just one part of the contact person's address. So, it doesn't really relate 1:1 to something in most data sets.

**Comment by zhengj2007** [comment]
Sorry I put the wrong IDs for the terms. It should be:
OBIB:0000656 biobank location ISO 3166-1 alpha-2 code
OBIB:0000640 ISO 3166-1 alpha-2 code for biobank contact person

So, I removed the alternative term for OBIB:0000640.
