### ISSUE TITLE
'role in human social processes' (OMRSE:00000024) has been deprecated and replaced

### ISSUE THREAD

**Issue by dillerm** [biobanking/biobanking#89]
In the future we plan on reaching out to developers of ontologies that import our classes to get their input prior to making such changes, but we have replaced this class with another one with the same label: 'role in human social processes' (OMRSE:00002072). The only change to the class was to the subClassOf axiom, which we changed from "inheres-in only human or organization" to "inhere-in only 'material entity'."

**Comment by cstoeckert** [comment]
@StroemPhi I ran into the same problem and will make a priority of fixing this. Thanks.
