### ISSUE TITLE
my homework- creating an issue in GitHub- leveraging biobanking use cases from HL7 

### ISSUE THREAD

**Issue by hjellis** [biobanking/biobanking#9]
i was given a document about HL7 use cases for biobanking from a Duke colleague. it is called
*\* "HL7 Domain Analysis Model: Specimen, Release 1, April 2015
HL7 Informative Document: HL7 DAM SPECIMEN, R1
A Technical Report prepared by Health Level Seven International and registered with ANSI: 5/31/2015."**

I will be researching the licensing/IP rules about this document to determine if we can consider the existing use cases as we prioritize our use cases going forward.

**Comment by cstoeckert** [comment]
Thanks Helena!
Chris

**Comment by hjellis** [comment]
I confirmed with our in house HL7 member that this document is publicly available and we can use it. Furthermore I am covered by Dukes HL7 membership. I will therefore upload the document

-Helena

On Apr 21, 2016, at 5:00 PM, cstoeckert <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks Helena!
Chris

> On Apr 21, 2016, at 4:58 PM, hjellis <notifications@github.com<mailto:notifications@github.com>> wrote:
>
> i was given a document about HL7 use cases for biobanking from a Duke colleague. it is called
> ** "HL7 Domain Analysis Model: Specimen, Release 1, April 2015
> HL7 Informative Document: HL7 DAM SPECIMEN, R1
> A Technical Report prepared by Health Level Seven International and registered with ANSI: 5/31/2015."**
>
> I will be researching the licensing/IP rules about this document to determine if we can consider the existing use cases as we prioritize our use cases going forward.
>
> -
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub <https://github.com/biobanking/biobanking/issues/9>


-

**Comment by hjellis** [comment]
[HL7_DAM_Specimen_R1_INFORM_2015APR (5).pdf](https://github.com/biobanking/biobanking/files/251040/HL7_DAM_Specimen_R1_INFORM_2015APR.5.pdf)

**Comment by cstoeckert** [comment]
I have generated an OBO/OBI model of Use Case 1. I'm including an image from the cmap (github won't let me attach it here). It was pretty quick and straightforward to do.
![hl7dam-cdiscusecase1](https://cloud.githubusercontent.com/assets/9141037/15728930/c71901e0-282d-11e6-8601-2bf658f2af6f.jpg)

**Comment by hjellis** [comment]
Thanks for reopening Chris, I couldn’t figure out how to do it.

**Comment by masciam** [comment]
I am not sure who is the participant in OBI "nuclei acid extraction" and "OBI planned process"

[Figure extraxction.pdf](https://github.com/biobanking/biobanking/files/296071/Figure.extraxction.pdf)

**Comment by masciam** [comment]
never mind I figured out I couldn 't see the figure clearly.

**Comment by masciam** [comment]
I think is great! I just added a couple of relations to link some more term, not necessary but may be may be useful.
[additional relation AMM.pdf](https://github.com/biobanking/biobanking/files/296189/additional.relation.AMM.pdf)

**Comment by hjellis** [comment]
[cdisc biospecimen pharmacogenomics-genetics.pdf](https://github.com/biobanking/biobanking/files/296432/cdisc.biospecimen.pharmacogenomics-genetics.pdf)

**Comment by cstoeckert** [comment]
Terms from this use case missing in OBIB were added. See issue #15 
health care encounter
medical device
genetic characteristics information
in vitro transcription
